### PR TITLE
readme: move to shields.io and format

### PR DESCRIPTION
**Pull request by yuanyiwei**
### Checklist

- [x] 更新 README

(如果方便的话, 可以简述一下您所做的改动)

更新 README：microbadger 迁移到 shields.io，更新 README License

### CODE REVIEW

**Comment by myl7** [comment]
Which formatter do you ues? Maybe we can configure it in CI.

**Comment by iBug** [comment]
Now that shields.io badges have only one piece of information per badge (either image size or layer count), what about adding two badges for each image, so we still have both pieces of info as before?

**Comment by yuanyiwei** [comment]
> Which formatter do you ues? Maybe we can configure it in CI.

是 prettier，目前 website 在用，这里就一个 Readme 是 md 感觉没有必要

**Comment by yuanyiwei** [comment]
> Now that shields.io badges have only one piece of information per badge (either image size or layer count), what about adding two badges for each image, so we still have both pieces of info as before?

image

可以看到原来的 image size 是不起作用的，再加一个 badge 倒也可以

**Comment by knight42** [comment]
> Which formatter do you ues? Maybe we can configure it in CI.

+1。感觉可以在 github action 里加一个 step 来检查一下 README 的格式

**Comment by iBug** [comment]
@myl7 @knight42 I feel it like an overkill. This is not a documentation-heavy repo (unlike our website or Linux101) so I find little value in checking README on every CI run.

**Comment by knight42** [comment]
> @myl7 @knight42 I feel it like an overkill. This is not a documentation-heavy repo (unlike our website or Linux101) so I find little value in checking README on every CI run.

我觉得这个问题取决于我们是否希望检查 README 的格式。如果是的话我觉得最好的方法就是在每次 CI 的时候检查，而不是某个人某天突然想起来了然后检查一下。

**Comment by yuanyiwei** [comment]
> > @myl7 @knight42 I feel it like an overkill. This is not a documentation-heavy repo (unlike our website or Linux101) so I find little value in checking README on every CI run.
> 
> 我觉得这个问题取决于我们是否希望检查 README 的格式。如果是的话我觉得最好的方法就是在每次 CI 的时候检查，而不是某个人某天突然想起来了然后检查一下。

我觉得每次检查 README 在这种仓库中没有必要

比如这次 pr 在格式上最大的更新是改变一些二级标题（随手改的，因为 TOC 看起来很诡异），而这个也不是经常会发生的
主要是把 microbadger 迁移到 shields.io（因为 microbadger.com 要关了），更新 GitHub release License

**Review by myl7 — APPROVED** [review]
Though formatting makes the changes complicated, and I personally do not agree to use spaces to aligning, the purpose which is migrating to shields.io is just archived. LGTM.

**Pull request merged**
